# Site settings
title: Your Site Title
description: A simple Jekyll site hosted on GitHub Pages
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
